spring:
  psql:
    datasource:
      url: jdbc:postgresql://postgres:5432/products
      username: postgres
      password: postgres
  mssql:
    datasource:
      url: jdbc:sqlserver://84.252.128.13:1433;databaseName=access-log;encrypt=true;trustServerCertificate=true
      username: sa
      password: password123!

products:
  url: https://products:1516
